* Erlang/OTC - Open Telecom Codec

  This library tries to implement encoding and decoding for different
  telco protocols. The aim is to support the newest release of each
  spec, if not stated otherwise.

  Encoded format is a binary, and decoded format is a map.

  If a field or message is not supported, the library should not crash
  but instead return some error-tuple or atom.

  Decoding should preferably be strict, and follow the rules from the
  specification.  Encoding on the other hand, should be lenient, but
  if format is incorrect, then log a warning. The idea behind this is
  that the user knows best what to send, but might need guidance.

* Linguistics

  decode - function that converts from binary format to an Erlang map

  parse - function that converts from UMTS magic number to Erlang atom

  encode - function that converts from Erlang map to binary format

  compose - function that converts from Erlang atom to UMTS magic number

* Codecs

| Name    | Spec                          | Encode | Decode | Production Tested | Notes                                            |
|---------+-------------------------------+--------+--------+-------------------+--------------------------------------------------+
| M3UA    | IETF RFC 4666 September 2006  | X      | X      |                   |                                                  |
| M2PA    | IETF RFC 4165 September 2005  | X      | X      |                   |                                                  |
| MTP3    | ITU-T Q.704 (07/96) July 1996 | X      | X      |                   |                                                  |
| SCCP    | ITU-T Q.713 (03/2001)         | X      | X      |                   |                                                  |
| L3      | 3GPP TS 24.007 V16.5.0        | X      | X      |                   |                                                  |
| NAS EPS | 3GPP TS 24.301 V16.8.0        | /      | /      |                   | Messages are de-/encoded, but missing parameters |
| NAS 5GS | 3GPP TS 24.501 V16.10.0       | /      | /      |                   | Messages are de-/encoded, but missing parameters |
