

%% 2.1.3.  Message Class
-define(M2PA_MSG_CLASS_MSGS, 11).

%% 2.1.4.  Message Type
-define(M2PA_MSG_TYPE_USER_DATA, 1).
-define(M2PA_MSG_TYPE_LINK_STATUS, 2).


%% 2.3.2.  Link Status
-define(LINK_STATUS_STATE_ALIGNMENT, 1).
-define(LINK_STATUS_STATE_PROVING_NORMAL, 2).
-define(LINK_STATUS_STATE_PROVING_EMERGENCY, 3).
-define(LINK_STATUS_STATE_READY, 4).
-define(LINK_STATUS_STATE_PROCESSOR_OUTAGE, 5).
-define(LINK_STATUS_STATE_PROCESSOR_RECOVERED, 6).
-define(LINK_STATUS_STATE_BUSY, 7).
-define(LINK_STATUS_STATE_BUSY_ENDED, 8).
-define(LINK_STATUS_STATE_OUT_OF_SERVICE, 9).

