
%% 3.1.2.  Message Classes and Types
-define(M3UA_MSG_CLASS_MGMT, 0).
-define(M3UA_MSG_CLASS_TM, 1).
-define(M3UA_MSG_CLASS_SSNM, 2).
-define(M3UA_MSG_CLASS_ASPSM, 3).
-define(M3UA_MSG_CLASS_ASPTM, 4).
-define(M3UA_MSG_CLASS_RKM, 9).

%% Management (MGMT) Messages
-define(M3UA_MGMT_TYPE_ERR, 0).
-define(M3UA_MGMT_TYPE_NTFY, 1).

%% Transfer Messages
-define(M3UA_TM_TYPE_DATA, 1).

%% SS7 Signalling Network Management (SSNM) Messages
-define(M3UA_SSNM_TYPE_DUNA, 1).
-define(M3UA_SSNM_TYPE_DAVA, 2).
-define(M3UA_SSNM_TYPE_DAUD, 3).
-define(M3UA_SSNM_TYPE_SCON, 4).
-define(M3UA_SSNM_TYPE_DUPU, 5).
-define(M3UA_SSNM_TYPE_DRST, 6).

%% ASP State Maintenance (ASPSM) Messages
-define(M3UA_ASPSM_TYPE_ASPUP, 1).
-define(M3UA_ASPSM_TYPE_ASPDN, 2).
-define(M3UA_ASPSM_TYPE_BEAT, 3).
-define(M3UA_ASPSM_TYPE_ASPUP_ACK, 4).
-define(M3UA_ASPSM_TYPE_ASPDN_ACK, 5).
-define(M3UA_ASPSM_TYPE_BEAT_ACK, 6).

%% ASP Traffic Maintenance (ASPTM) Messages
-define(M3UA_ASPTM_TYPE_ASPAC, 1).
-define(M3UA_ASPTM_TYPE_ASPIA, 2).
-define(M3UA_ASPTM_TYPE_ASPAC_ACK, 3).
-define(M3UA_ASPTM_TYPE_ASPIA_ACK, 4).

%% Routing Key Management (RKM) Messages
-define(M3UA_RKM_TYPE_REG_REQ, 1).
-define(M3UA_RKM_TYPE_REG_RSP, 2).
-define(M3UA_RKM_TYPE_DEREG_REQ, 3).
-define(M3UA_RKM_TYPE_DEREG_RSP, 4).

%% 3.2 Variable-Length Parameters
-define(M3UA_TAG_INFO_STRING, 16#0004).
-define(M3UA_TAG_ROUTING_CONTEXT, 16#0006).
-define(M3UA_TAG_DIAGNOSTIC_INFORMATION, 16#0007).
-define(M3UA_TAG_HEARTBEAT_DATA, 16#0009).
-define(M3UA_TAG_TRAFFIC_MODE_TYPE, 16#000b).
-define(M3UA_TAG_ERROR_CODE, 16#000c).
-define(M3UA_TAG_STATUS, 16#000d).
-define(M3UA_TAG_ASP_IDENTIFIER, 16#0011).
-define(M3UA_TAG_AFFECTED_POINT_CODE, 16#0012).
-define(M3UA_TAG_CORRELATION_ID, 16#0013).
-define(M3UA_TAG_NETWORK_APPEARANCE, 16#0200).
-define(M3UA_TAG_USER_AND_CAUSE, 16#0204).
-define(M3UA_TAG_CONGESTION_INDICATIONS, 16#0205).
-define(M3UA_TAG_CONCERNED_DESTINATION, 16#0206).
-define(M3UA_TAG_ROUTING_KEY, 16#0207).
-define(M3UA_TAG_REGISTRATION_RESULT, 16#0208).
-define(M3UA_TAG_DEREGISTRATION_RESULT, 16#0209).
-define(M3UA_TAG_LOCAL_ROUTING_KEY_IDENTIFIER, 16#020a).
-define(M3UA_TAG_DESTINATION_POINT_CODE, 16#020b).
-define(M3UA_TAG_SERVICE_INDICATORS, 16#020c).
-define(M3UA_TAG_ORIGINATING_POINT_CODE_LIST, 16#020e).
-define(M3UA_TAG_PROTOCOL_DATA, 16#0210).
-define(M3UA_TAG_REGISTRATION_STATUS, 16#0212).
-define(M3UA_TAG_DEREGISTRATION_STATUS, 16#0213).
