name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{matrix.erlang.os}}
    name: Erlang/OTP ${{matrix.erlang.otp}} / rebar3 ${{matrix.erlang.rebar3}}
    strategy:
      matrix:
        erlang:
          - otp: "27.1.2"
            rebar3: "3.22.1"
            os: ubuntu-24.04
    env:
      OTC_NO_DIA: true
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.erlang.otp}}
          rebar3-version: ${{matrix.erlang.rebar3}}
      - run: rebar3 eunit
